/**
 * Created by WAN on 2017/9/8.
 */

'use strict';
// 获取各种排行榜列表
export const GET_RANK_LIST_ACTION = 'GET_RANK_LIST_ACTION';
//根据id获取排行榜详情信息 周
export const GET_WEEK_RANK_DETAIL_LIST_ACTION = 'GET_WEEK_RANK_DETAIL_LIST_ACTION';
//根据id获取排行榜详情信息 月
export const GET_MONTH_RANK_DETAIL_LIST_ACTION = 'GET_MONTH_RANK_DETAIL_LIST_ACTION';
//根据id获取排行榜详情信息 总
export const GET_TOTAL_RANK_DETAIL_LIST_ACTION = 'GET_TOTAL_RANK_DETAIL_LIST_ACTION';
//获取书籍详情
export const GET_BOOK_DETAIL_ACTION = 'GET_BOOK_DETAIL_ACTION';
//设置书籍加载信息的状态
export const SET_LOADING_NEW_STATE_ACTION = 'SET_LOADING_NEW_STATE_ACTION';
//获取书籍的章节目录
export const GET_CHAPTERS_LIST_ACTION = 'GET_CHAPTERS_LIST_ACTION';
//清除之前获取书籍的章节目录
export const CLEAR_CHAPTERS_LIST_ACTION = 'CLEAR_CHAPTERS_LIST_ACTION';
//请求资源无效
export const REQUEST_CHAPTERS_SOURCE_INVALID = 'REQUEST_CHAPTERS_SOURCE_INVALID';
//恢复初始状态
export const RESTORE_REQUEST_CHAPTERS_SOURCE_INVALID = 'RESTORE_REQUEST_CHAPTERS_SOURCE_INVALID';
//获取章节详情
export const GET_CHAPTER_DETAIL_ACTION = 'GET_CHAPTER_DETAIL_ACTION';

//获取数据库中的书籍信息
export const GET_BOOK_SHELVES_ACTION = 'GET_BOOK_SHELVES_ACTION';
//获取数据库中书籍的最新章节信息
export const GET_SHELVES_BOOK_DETAIL_ACTION = 'GET_SHELVES_BOOK_DETAIL_ACTION';


//书单
//获取书单信息
export const GET_BOOK_LIST_ACTION = 'GET_BOOK_LIST_ACTION';
//获取书单详情
export const GET_BOOK_LIST_DETAIL_ACTION = 'GET_BOOK_LIST_DETAIL_ACTION';

//类别
//获取类别信息
export const GET_CATEGORY_LIST_ACTION = 'GET_CATEGORY_LIST_ACTION';
//获取二级类别信息
export const GET_CATEGORY_LIST_V2_ACTION = 'GET_CATEGORY_LIST_V2_ACTION';
//获取类别详情
export const GET_SORT_DETAIL_LIST_ACTION = 'GET_SORT_DETAIL_LIST_ACTION';

//搜索
//搜索结果状态
export const SET_BOOK_LOADING_NEW_STATE_ACTION = 'SET_BOOK_LOADING_NEW_STATE_ACTION';
//获取搜索热词
export const GET_SEARCH_HOT_WORLD_ACTION = 'GET_SEARCH_HOT_WORLD_ACTION';
//获取搜索结果
export const GET_SEARCH_BOOK_LIST_ACTION = 'GET_SEARCH_BOOK_LIST_ACTION';